---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.72, CPAN::Meta::Converter version 2.120630'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: AnyEvent-Fork
no_index:
  directory:
    - t
    - inc
requires:
  AnyEvent: 6
  IO::FDPass: 0.2
  Proc::FastSpawn: 0.1
  common::sense: 3.6
version: 1.2
